services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_USER: expenses_user
      MYSQL_PASSWORD: App@123
      MYSQL_DATABASE: expenses_tracker
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appbridge
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uexpenses_user","-pApp@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: always

  java-app:
    build: .
    image: expensetracker_v3
    container_name: expensetracker
    environment:
      SPRING_DATASOURCE_USERNAME: expenses_user
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_PASSWORD: App@123
    ports:
      - "8080:8080"
    networks:
      - appbridge
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - java-app
      - mysql
    networks:
      - appbridge

networks:
  appbridge:
    name: appbridge

volumes:
  mysql-data:
    name: mysql-data
